name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Lint code
    - name: Run linter
      run: |
        pip install flake8
        flake8 .

    # Step 5: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t flask-docker-app .

    # Step 6: Deploy to EC2
    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker stop flask-docker-app || true
          docker rm flask-docker-app || true
          docker run -d -p 5000:5000 --name flask-docker-app flask-docker-app
